---
- hosts: localhost
  tasks:
          - name: Add OSQuery repo (CentOS)
            yum: 
                name: https://osquery-packages.s3.amazonaws.com/centos7/noarch/osquery-s3-centos7-repo-1-0.0.noarch.rpm 
                state: present
