---
- hosts: localhost
  tasks:
          - name: Add OSQuery repo (CentOS)
            shell: rpm -ivh https://osquery-packages.s3.amazonaws.com/centos7/noarch/osquery-s3-centos7-repo-1-0.0.noarch.rpm 

          - name: Install OSQuery
            shell: yum install osquery
