---
- hosts: localhost
  tasks:
          - name: Add OSQuery repo (CentOS)
            yum: 
                name: https://osquery-packages.s3.amazonaws.com/centos7/noarch/osquery-s3-centos7-repo-1-0.0.noarch.rpm 
                state: present

          - name: Install OSQuery with yum
            yum:
                name: osquery
                state: present

          - name: Install dependencies
            yum:
                name: yum-utils
                state: latest
            yum:
                name: device-mapper-persistent-data
                state: latest
            yum:
                name: lvm2
                state: latest

          - name: Add docker repo
            yum_repository:
                name: docker-ce
                description: docker community edition latest
                baseurl: https://download.docker.com/linux/centos/

          - name: Install docker
            yum:
                name: docker-ce
                state: present
